#!/usr/bin/env bats

# moltis soul HTTP K/V integration test
# Verifies b00t soul serve API works as moltis memory backend
# Generated by pi (gemma4) + fixed by executive

load 'test_helper/bats-support/load'
load 'test_helper/bats-assert/load'

SOUL_PID_FILE="/tmp/bats-soul-serve.pid"

setup() {
  b00t soul serve &
  echo $! > "$SOUL_PID_FILE"
  sleep 2
}

teardown() {
  if [ -f "$SOUL_PID_FILE" ]; then
    kill "$(cat $SOUL_PID_FILE)" 2>/dev/null
    wait "$(cat $SOUL_PID_FILE)" 2>/dev/null
    rm -f "$SOUL_PID_FILE"
  fi
}

@test "set key" {
  run curl -s -o /dev/null -w "%{http_code}" -X POST http://127.0.0.1:7700/v1/kv/moltis_integration_test \
    -H "Content-Type: application/json" -d '{"value":"ok"}'
  assert_output "200"
}

@test "get key returns ok" {
  # pre-condition: key must exist
  curl -s -X POST http://127.0.0.1:7700/v1/kv/moltis_integration_test \
    -H "Content-Type: application/json" -d '{"value":"ok"}'
  run curl -s http://127.0.0.1:7700/v1/kv/moltis_integration_test
  assert_output --partial "ok"
}

@test "delete key then 404" {
  curl -s -X POST http://127.0.0.1:7700/v1/kv/moltis_integration_test \
    -H "Content-Type: application/json" -d '{"value":"ok"}'
  curl -s -X DELETE http://127.0.0.1:7700/v1/kv/moltis_integration_test
  run curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:7700/v1/kv/moltis_integration_test
  assert_output "404"
}
