[b00t]
name = "filesystem"
type = "mcp"
hint = "MCP server"

entangled_cli = ["filesystem.cli"]

[[b00t.gate]]
command = "npx"

[[b00t.gate]]
env = "FILESYSTEM_ACCESS"

[[b00t.mcp.stdio]]
args = ["-y", "@modelcontextprotocol/server-filesystem"]
command = "npx"
requires = ["node"]
priority = 0
transport = "stdio"
