#!/usr/bin/env python3
"""Generate deterministic Claude marketplace and MCP bundle recipes for b00t."""

from __future__ import annotations

import argparse
import json
import re
import shutil
from pathlib import Path
from typing import Any


def _slugify(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")


def _read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


_AUTO_NOTE = "AUTO-GENERATED by scripts/generate_claude_marketplace.py — DO NOT EDIT. Rebuild: just marketplace-generate"


def _dump_json(value: Any) -> str:
    return json.dumps(value, indent=2, sort_keys=True, ensure_ascii=True) + "\n"


def _write_json(path: Path, value: Any, check: bool) -> bool:
    # Inject _note as first key (sorts before all alpha keys due to underscore prefix).
    if isinstance(value, dict):
        value = {"_note": _AUTO_NOTE, **value}
    payload = _dump_json(value)
    if path.exists() and path.read_text(encoding="utf-8") == payload:
        return False
    if check:
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(payload, encoding="utf-8")
    return True


def _load_role_server(
    role_server: dict[str, Any],
    registry: dict[str, dict[str, Any]],
) -> dict[str, Any]:
    registry_id = role_server.get("registry_id")
    if registry_id:
        if registry_id not in registry:
            raise ValueError(f"registry_id not found: {registry_id}")
        return dict(registry[registry_id])

    required = ["id", "name", "description", "config"]
    missing = [field for field in required if field not in role_server]
    if missing:
        raise ValueError(f"role external server missing fields {missing}: {role_server}")

    entry = dict(role_server)
    entry.setdefault("source", "external")
    entry.setdefault("version", "0.1.0")
    entry.setdefault("tags", [])
    entry.setdefault("references", [])
    return entry


def _recipe_file_name(server_id: str, server_name: str) -> str:
    return f"{_slugify(server_id)}--{_slugify(server_name)}.json"


def _has_stale_files(directory: Path, expected_paths: set[Path], recursive: bool) -> bool:
    """Return True if *directory* contains any file not present in *expected_paths*."""
    if not directory.exists():
        return False
    glob = directory.rglob("*.json") if recursive else directory.glob("*.json")
    return any(f not in expected_paths for f in glob)


def generate(
    repo_root: Path,
    registry_path: Path,
    roles_path: Path,
    check: bool,
) -> int:
    changed = False
    registry: dict[str, dict[str, Any]] = _read_json(registry_path)
    roles_doc: dict[str, Any] = _read_json(roles_path)

    recipes_root = repo_root / ".claude-plugin" / "recipes"
    mcp_recipe_dir = recipes_root / "mcp-servers"
    roles_recipe_dir = recipes_root / "roles"
    skills_recipe_dir = recipes_root / "skills"
    generated_roles_plugin_dir = repo_root / "plugins" / "roles"
    generated_skills_plugin_dir = repo_root / "plugins" / "skills"

    # Flat recipe directories whose contents are fully regenerated each run.
    # In check mode we leave them intact and compare against expected_paths at the end.
    # In write mode we nuke them first so stale files are automatically removed.
    if not check:
        for d in (
            mcp_recipe_dir,
            roles_recipe_dir,
            skills_recipe_dir,
            generated_roles_plugin_dir,
            generated_skills_plugin_dir,
        ):
            if d.exists():
                shutil.rmtree(d)
        mcp_recipe_dir.mkdir(parents=True, exist_ok=True)
        roles_recipe_dir.mkdir(parents=True, exist_ok=True)
        skills_recipe_dir.mkdir(parents=True, exist_ok=True)

    # Track every path we intend to produce; used for stale-file detection in check mode.
    expected_paths: set[Path] = set()

    marketplace_cfg = roles_doc["marketplace"]
    base_plugins = list(roles_doc.get("base_plugins", []))

    all_servers: list[dict[str, Any]] = []
    for server_id in sorted(registry):
        entry = dict(registry[server_id])
        entry.setdefault("source", "registry")
        all_servers.append(entry)

    bundle_plugins: list[dict[str, Any]] = []
    bundle_entries = list(roles_doc.get("bundles", []))
    if not bundle_entries:
        bundle_entries = list(roles_doc.get("roles", []))
    bundle_entries = sorted(bundle_entries, key=lambda x: x["id"])

    # Emit per-server recipes from registry first.
    for server in all_servers:
        sid = str(server["id"])
        sname = str(server.get("name", sid))
        mcp_key = sname
        recipe = {
            "id": sid,
            "name": sname,
            "description": server.get("description", ""),
            "version": server.get("version", "0.1.0"),
            "source": server.get("source", "registry"),
            "tags": list(server.get("tags", [])),
            "references": list(server.get("references", [])),
            "mcpServers": {
                mcp_key: dict(server.get("config", {})),
            },
        }
        recipe_path = mcp_recipe_dir / _recipe_file_name(sid, sname)
        expected_paths.add(recipe_path)
        changed |= _write_json(recipe_path, recipe, check)

    if not check:
        generated_roles_plugin_dir.mkdir(parents=True, exist_ok=True)
        generated_skills_plugin_dir.mkdir(parents=True, exist_ok=True)

    for bundle in bundle_entries:
        bundle_type = str(bundle.get("type", "role"))
        if bundle_type not in {"role", "skill"}:
            raise ValueError(f"unsupported bundle type: {bundle_type}")
        bundle_id = bundle["id"]
        bundle_name = bundle.get("name", bundle_id)
        bundle_servers = [_load_role_server(item, registry) for item in bundle.get("servers", [])]

        # Stable order by server id.
        bundle_servers = sorted(bundle_servers, key=lambda s: str(s["id"]))

        merged_mcp_servers: dict[str, Any] = {}
        server_refs: list[dict[str, str]] = []
        for server in bundle_servers:
            sid = str(server["id"])
            sname = str(server["name"])
            recipe_name = _recipe_file_name(sid, sname)
            recipe = {
                "id": sid,
                "name": sname,
                "description": server.get("description", ""),
                "version": server.get("version", "0.1.0"),
                "source": server.get("source", "registry"),
                "tags": list(server.get("tags", [])),
                "references": list(server.get("references", [])),
                "mcpServers": {
                    sname: dict(server.get("config", {})),
                },
            }
            recipe_path = mcp_recipe_dir / recipe_name
            expected_paths.add(recipe_path)
            changed |= _write_json(recipe_path, recipe, check)

            # Keep names deterministic and unique.
            mcp_key = sname
            if mcp_key in merged_mcp_servers:
                mcp_key = f"{sname}-{_slugify(sid)}"
            merged_mcp_servers[mcp_key] = dict(server.get("config", {}))
            server_refs.append({
                "id": sid,
                "name": sname,
                "recipe": f"../mcp-servers/{recipe_name}",
            })

        bundle_recipe = {
            "id": bundle_id,
            "type": bundle_type,
            "name": bundle_name,
            "description": bundle.get("description", ""),
            "tags": list(bundle.get("tags", [])),
            "servers": server_refs,
            "mcpServers": merged_mcp_servers,
        }
        recipe_dir = roles_recipe_dir if bundle_type == "role" else skills_recipe_dir
        bundle_recipe_path = recipe_dir / f"{bundle_id}.json"
        expected_paths.add(bundle_recipe_path)
        changed |= _write_json(bundle_recipe_path, bundle_recipe, check)

        plugin_root = generated_roles_plugin_dir if bundle_type == "role" else generated_skills_plugin_dir
        bundle_plugin_dir = plugin_root / bundle_id / ".claude-plugin"
        bundle_plugin_manifest = {
            "name": f"{bundle_type}-{bundle_id}",
            "version": marketplace_cfg.get("version", "0.1.0"),
            "description": f"Installable MCP {bundle_type} bundle: {bundle_name}",
            "author": {"name": marketplace_cfg.get("owner", "elasticdotventures")},
            "keywords": list(bundle.get("tags", [])),
            "capabilities": {
                "skills": False,
                "commands": False,
                "hooks": False,
                "mcp": True,
            },
            "metadata": {
                "category": f"mcp-{bundle_type}-bundle",
                bundle_type: bundle_id,
                "recipe": f"../../../.claude-plugin/recipes/{bundle_type}s/{bundle_id}.json",
            },
        }
        plugin_manifest_path = bundle_plugin_dir / "plugin.json"
        expected_paths.add(plugin_manifest_path)
        changed |= _write_json(plugin_manifest_path, bundle_plugin_manifest, check)

        bundle_plugins.append(
            {
                "name": f"{bundle_type}-{bundle_id}",
                "source": f"./plugins/{bundle_type}s/{bundle_id}",
                "description": bundle.get("description", ""),
                "version": marketplace_cfg.get("version", "0.1.0"),
            }
        )

    marketplace = {
        "name": marketplace_cfg["name"],
        "owner": {"name": marketplace_cfg["owner"]},
        "metadata": {
            "description": marketplace_cfg["description"],
            "version": marketplace_cfg.get("version", "0.1.0"),
            "pluginRoot": marketplace_cfg.get("pluginRoot", "./plugins"),
        },
        "plugins": sorted(base_plugins + bundle_plugins, key=lambda p: p["name"]),
    }
    marketplace_path = repo_root / ".claude-plugin" / "marketplace.json"
    expected_paths.add(marketplace_path)
    changed |= _write_json(marketplace_path, marketplace, check)

    # Count expected MCP recipe files deterministically.
    # Filter by parent directory because expected_paths also contains marketplace.json,
    # index.json, bundle recipe files, and plugin manifests from other directories.
    expected_mcp_recipe_count = sum(1 for p in expected_paths if p.parent == mcp_recipe_dir)
    index = {
        "generated_at": "deterministic",
        "marketplace": marketplace_cfg["name"],
        "bundle_count": len(bundle_entries),
        "mcp_recipe_count": expected_mcp_recipe_count,
    }
    index_path = recipes_root / "index.json"
    expected_paths.add(index_path)
    changed |= _write_json(index_path, index, check)

    # In check mode, flag stale files in flat recipe directories that wouldn't be regenerated.
    if check:
        for gen_dir in (mcp_recipe_dir, roles_recipe_dir, skills_recipe_dir):
            changed |= _has_stale_files(gen_dir, expected_paths, recursive=False)
        for gen_dir in (generated_roles_plugin_dir, generated_skills_plugin_dir):
            changed |= _has_stale_files(gen_dir, expected_paths, recursive=True)

    if check and changed:
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", default=".", help="Repository root path")
    parser.add_argument(
        "--registry",
        default="mcp_registry.json",
        help="Path to mcp_registry.json (relative to repo-root)",
    )
    parser.add_argument(
        "--roles-config",
        default="config/claude-marketplace-roles.json",
        help="Path to role recipe config JSON (relative to repo-root)",
    )
    parser.add_argument("--check", action="store_true", help="Validate generated outputs without writing")
    args = parser.parse_args()

    repo_root = Path(args.repo_root).resolve()
    registry_path = (repo_root / args.registry).resolve()
    roles_path = (repo_root / args.roles_config).resolve()

    return generate(
        repo_root=repo_root,
        registry_path=registry_path,
        roles_path=roles_path,
        check=args.check,
    )


if __name__ == "__main__":
    raise SystemExit(main())
