#!/usr/bin/env bash
# ralph-issue.sh — codex worker + automated review per GH issue
# Usage: ./ralph-issue.sh <issue_num> <cluster> "<issue_title>"
# Pattern: codex exec → codex-powered review → gh comment
# RL: re-runs if review rejects until MAX_ITER or APPROVED

set -euo pipefail

ISSUE_NUM="${1:?issue_num required}"
CLUSTER="${2:?cluster required}"
ISSUE_TITLE="${3:?issue_title required}"
MAX_ITER="${MAX_ITER:-5}"
REPO="${REPO:-elasticdotventures/_b00t_}"

WORKDIR=$(mktemp -d /tmp/ralph-issue-${ISSUE_NUM}-XXXX)
PROMPT_FILE="${WORKDIR}/PROMPT.md"
CODEX_OUT="${WORKDIR}/codex-output.md"
REVIEW_OUT="${WORKDIR}/haiku-review.md"

# Limit how much Codex output is embedded directly into GitHub comments
MAX_CODEX_COMMENT_BYTES="${MAX_CODEX_COMMENT_BYTES:-60000}"
CODEX_SNIPPET="${WORKDIR}/codex-output-snippet.md"
if [ -f "${CODEX_OUT}" ]; then
    # Create a bounded snippet of the Codex output for safe inclusion in comments
    head -c "${MAX_CODEX_COMMENT_BYTES}" "${CODEX_OUT}" > "${CODEX_SNIPPET}" || true
    # If truncated, append a short notice
    if [ "$(wc -c < "${CODEX_OUT}" 2>/dev/null || echo 0)" -gt "${MAX_CODEX_COMMENT_BYTES}" ]; then
        {
            echo
            echo
            echo "[...codex output truncated to first ${MAX_CODEX_COMMENT_BYTES} bytes for GitHub comment safety...]"
        } >> "${CODEX_SNIPPET}"
    fi
else
    : > "${CODEX_SNIPPET}"
fi

ITER=0

cleanup() { rm -rf "${WORKDIR}"; }
trap cleanup EXIT

log() { echo "[ralph-issue #${ISSUE_NUM}] $*" >&2; }

# Fetch full issue body for context
ISSUE_BODY=$(gh issue view "${ISSUE_NUM}" --repo "${REPO}" --json body -q '.body' 2>/dev/null || echo "(no body)")

cat > "${PROMPT_FILE}" <<PROMPT
# Hive Maintenance: Issue #${ISSUE_NUM} — ${CLUSTER}
## Title: ${ISSUE_TITLE}

## Issue Body
${ISSUE_BODY}

## Your Mission
Analyze this GitHub issue in the context of the b00t codebase.
Produce a concise technical investigation report with:
1. **Root cause / scope** — what does this touch in the codebase?
2. **Proposed approach** — concrete next steps (code, config, docs)
3. **Effort estimate** — S/M/L
4. **Dependencies** — any blocking issues or prereqs
5. **Recommendation** — DELEGATE_CODEX | NEEDS_HUMAN | CLOSE_WONTFIX | ALREADY_DONE

Be laconic. Use b00t idioms. Reference specific files/paths where relevant.
Do NOT make code changes — investigation only.
Output in markdown.
PROMPT

while [[ ${ITER} -lt ${MAX_ITER} ]]; do
    ITER=$((ITER + 1))
    log "iter ${ITER}/${MAX_ITER} — codex exec"

    # codex exec: non-interactive investigation via stdin (avoids arg-length limits)
    # timeout 300s per attempt; disk-full-read-access for codebase scan
    timeout 300 codex exec \
        --config 'sandbox_permissions=["disk-full-read-access"]' \
        - < "${PROMPT_FILE}" \
        > "${CODEX_OUT}" 2>&1 || {
            log "⚠️ codex exec failed/timeout iter ${ITER} (exit $?)"
            continue
        }

    log "codex done — codex review"

    # codex review: fresh codex instance as quality gate (avoids nested CLAUDE env)
    # build review prompt file, pipe via stdin to fresh codex instance
    cat > "${WORKDIR}/review-prompt.md" <<REVIEW_PROMPT
You are a strict b00t hive QA reviewer. No shell tools needed — just read and respond.
Review this issue analysis for issue #${ISSUE_NUM}: '${ISSUE_TITLE}'
Accept criteria: addresses root cause, has concrete proposal, has recommendation field.
Respond EXACTLY with one of (no other text, no explanation):
  APPROVED: <one-line summary>
  REJECTED: <specific reason>

Analysis to review:
$(cat ${CODEX_OUT})
REVIEW_PROMPT
    REVIEW=$(timeout 120 codex exec \
        --config 'sandbox_permissions=["disk-full-read-access"]' \
        - < "${WORKDIR}/review-prompt.md" 2>/dev/null \
        | grep -E "^(APPROVED|REJECTED):" | head -1 || true)

    echo "${REVIEW}" > "${REVIEW_OUT}"
    log "review: ${REVIEW}"

    if echo "${REVIEW}" | grep -q "^APPROVED:"; then
        SUMMARY=$(echo "${REVIEW}" | sed 's/^APPROVED: //')
        # Post findings as GH issue comment
        gh issue comment "${ISSUE_NUM}" \
            --repo "${REPO}" \
            --body "## 🤖 Hive Maintenance Report (ralph-issue v${ITER})

**Cluster:** ${CLUSTER}
**Reviewed by:** claude-haiku-4-5-20251001 ✅

${REVIEW}

<details><summary>Full codex analysis</summary>

$(cat ${CODEX_SNIPPET})

</details>

---
*Generated by scripts/hive-maintenance/ralph-issue.sh — iter ${ITER}/${MAX_ITER}*" 2>&1

        log "✅ posted to #${ISSUE_NUM} — APPROVED: ${SUMMARY}"
        exit 0
    fi

    log "REJECTED iter ${ITER} — refining prompt"
    # Append rejection feedback to prompt for next iter
    cat >> "${PROMPT_FILE}" <<RETRY

## Previous Attempt Rejected
Haiku reviewer said: $(cat ${REVIEW_OUT})
Please address the specific concern above in your next analysis.
RETRY
done

log "❌ MAX_ITER ${MAX_ITER} reached without approval for #${ISSUE_NUM}"
# Post partial findings with warning
gh issue comment "${ISSUE_NUM}" \
    --repo "${REPO}" \
    --body "## ⚠️ Hive Maintenance: Partial Report (${MAX_ITER} iters, not approved)

**Cluster:** ${CLUSTER}
**Status:** Needs human review — haiku QA did not approve after ${MAX_ITER} iterations

Last reviewer feedback:
$(cat ${REVIEW_OUT} 2>/dev/null || echo 'N/A')

<details><summary>Last codex output</summary>
$(cat ${CODEX_SNIPPET} 2>/dev/null || echo 'N/A')
</details>" 2>&1 || true

exit 1
