#!/bin/bash
# ufo-adoption-report.sh — measured baseline of ufo-types adoption (#928)
# 🤓 #910 asks for a learn-topic knowledge map of which subsystems defer to
#    ufo-types. #905 warns against building "parallel vocabularies" instead
#    of adopting the shared ontology. Neither had a *measured* baseline, so
#    there was no way to tell whether adoption improves or regresses over
#    time. This script IS the baseline: every number below is one grep,
#    run live — never hand-copied into a doc that can drift silently.
#
# Emits a markdown table (matching the format landed in issue #928) to
# stdout. The committed doc at _b00t_/ufo-types-adoption-baseline.md is
# just this script's output pasted in — `--check` proves that by diffing
# live output against the committed file.
#
# Usage:
#   ufo-adoption-report.sh            # print the report to stdout
#   ufo-adoption-report.sh --check    # diff live report vs committed doc;
#                                      # PASS/FAIL, exit 0/1
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# _b00t_/scripts/ is always two levels below repo root — resolve via the
# script's own location, not `git rev-parse --show-toplevel` (this repo
# uses bare-repo + multiple worktrees, so "show-toplevel" assumptions
# don't hold — see check-submodule-drift.sh for the same pattern).
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
DOC_PATH="$REPO_ROOT/_b00t_/ufo-types-adoption-baseline.md"

CHECK=false
for arg in "$@"; do
    case "$arg" in
        --check) CHECK=true ;;
        *)
            echo "ufo-adoption-report.sh: unknown argument: $arg" >&2
            exit 2
            ;;
    esac
done

cd "$REPO_ROOT"

GREP_RS_OPTS=(--include=*.rs . --exclude-dir=vendor --exclude-dir=target)
GREP_TOML_OPTS=(--include=Cargo.toml . --exclude-dir=vendor --exclude-dir=target)

# --- crates depending on ufo-types -----------------------------------------
# Every crate-level Cargo.toml that references ufo-types, minus the
# workspace-root Cargo.toml (which only *declares* the workspace-level dep
# version under [workspace.dependencies] — it isn't itself a crate that
# "depends on" ufo-types).
mapfile -t UFO_DEP_CRATES < <(
    grep -rln 'ufo-types' "${GREP_TOML_OPTS[@]}" | grep -vE '^\.?/?Cargo\.toml$' | sed 's#^\./##' | sort
)
UFO_DEP_COUNT="${#UFO_DEP_CRATES[@]}"
UFO_DEP_NAMES=$(printf '%s, ' "${UFO_DEP_CRATES[@]%/Cargo.toml}")
UFO_DEP_NAMES="${UFO_DEP_NAMES%, }"

# --- impl Stereotyped for ---------------------------------------------------
mapfile -t STEREOTYPED_LINES < <(grep -rn 'impl.*Stereotyped for' "${GREP_RS_OPTS[@]}" | sed 's#^\./##' | sort)
STEREOTYPED_COUNT="${#STEREOTYPED_LINES[@]}"

# --- impl Satisfies<C> for --------------------------------------------------
mapfile -t SATISFIES_LINES < <(grep -rn 'impl.*Satisfies<' "${GREP_RS_OPTS[@]}" | sed 's#^\./##' | sort)
SATISFIES_COUNT="${#SATISFIES_LINES[@]}"

# --- b00t-cli depends on ufo-types? -----------------------------------------
if grep -q 'ufo-types' b00t-cli/Cargo.toml 2>/dev/null; then
    CLI_DEPENDS="yes"
else
    CLI_DEPENDS="no"
fi

# --- BootDatum / DatumType grounded in Stereotyped? -------------------------
mapfile -t GROUNDED_LINES < <(
    grep -rn 'impl Stereotyped for BootDatum\|impl Stereotyped for DatumType' "${GREP_RS_OPTS[@]}" | sed 's#^\./##' | sort
)
if [[ "${#GROUNDED_LINES[@]}" -ge 2 ]]; then
    GROUNDED="yes"
elif [[ "${#GROUNDED_LINES[@]}" -eq 1 ]]; then
    GROUNDED="partial"
else
    GROUNDED="no"
fi

# --- parallel-vocabulary heuristic (best-effort, NOT exhaustive) -----------
# Flags locally-defined struct/enum/trait whose name collides with a
# ufo-types module's exported concept. A name collision is a signal for
# human triage, not proof of duplication (could be a legitimate re-export,
# a newtype wrapper, or an unrelated concept that happens to share a name).
PARALLEL_VOCAB_PATTERN='^\s*(pub\s+)?(struct|enum|trait)\s+(Capability|CapabilityDomain|ActionRecord|StateObservation|DaredProposal|DaredDocument|DaredAcceptanceCriteria|IsoAuditable|Iso4217|Lei|OodaStateMachine|OodaPhase|OodaEvent|Stereotype)\b'
mapfile -t PARALLEL_VOCAB_HITS < <(
    grep -rnE "$PARALLEL_VOCAB_PATTERN" "${GREP_RS_OPTS[@]}" | sed 's#^\./##' | sort
)
PARALLEL_VOCAB_COUNT="${#PARALLEL_VOCAB_HITS[@]}"

# --- render report -----------------------------------------------------------
render_report() {
    cat <<EOF
<!-- REGENERATED by _b00t_/scripts/ufo-adoption-report.sh (issue #928). -->
<!-- Do not hand-edit the table below — run \`just ufo-adoption-report\` -->
<!-- and paste its output here. \`ufo-adoption-report.sh --check\` verifies -->
<!-- this file has zero drift against the live measurement. -->

## Measured state ($(date -u +%Y-%m-%d))

| metric | value |
|---|---|
| crates depending on ufo-types | ${UFO_DEP_COUNT} — ${UFO_DEP_NAMES} |
| impl Stereotyped for | ${STEREOTYPED_COUNT} |
| impl Satisfies<C> for | ${SATISFIES_COUNT} |
| b00t-cli depends on ufo-types | ${CLI_DEPENDS} |
| BootDatum / DatumType grounded | ${GROUNDED} |

### impl Stereotyped for — detail
EOF
    if [[ "$STEREOTYPED_COUNT" -eq 0 ]]; then
        echo "(none found)"
    else
        printf '%s\n' "${STEREOTYPED_LINES[@]}" | sed 's/^/- /'
    fi

    cat <<EOF

### impl Satisfies<C> for — detail
EOF
    if [[ "$SATISFIES_COUNT" -eq 0 ]]; then
        echo "(none found)"
    else
        printf '%s\n' "${SATISFIES_LINES[@]}" | sed 's/^/- /'
    fi

    cat <<EOF

### Parallel-vocabulary flags (heuristic — best-effort, NOT exhaustive)

Locally-defined \`struct\`/\`enum\`/\`trait\` whose name collides with a
ufo-types module concept (capability, dare, iso, stereotype/ooda). A hit
means "worth a human look", not "confirmed duplicate" — some may be
legitimate wrappers or unrelated same-named concepts.
EOF
    if [[ "$PARALLEL_VOCAB_COUNT" -eq 0 ]]; then
        echo "(none found)"
    else
        printf '%s\n' "${PARALLEL_VOCAB_HITS[@]}" | sed 's/^/- /'
    fi
}

REPORT="$(render_report)"

if [[ "$CHECK" == "true" ]]; then
    if [[ ! -f "$DOC_PATH" ]]; then
        echo "FAIL: committed doc not found at $DOC_PATH" >&2
        exit 1
    fi
    # Compare everything from the "## Measured state" heading onward in the
    # committed doc against the live report, ignoring the date on that
    # heading line (it's expected to change run-to-run, day-to-day).
    live_body=$(echo "$REPORT" | sed -E 's/^## Measured state \(.*\)$/## Measured state (DATE)/')
    doc_body=$(sed -n '/^<!-- REGENERATED/,$p' "$DOC_PATH" | sed -E 's/^## Measured state \(.*\)$/## Measured state (DATE)/')
    if [[ "$live_body" == "$doc_body" ]]; then
        echo "PASS: report regenerated, 0 drift vs committed"
        exit 0
    else
        echo "FAIL: live report drifted from committed doc ($DOC_PATH)" >&2
        echo "--- diff (committed vs live) ---" >&2
        diff <(echo "$doc_body") <(echo "$live_body") >&2 || true
        exit 1
    fi
else
    echo "$REPORT"
fi
