//! `b00t mise` — hidden passthrough bridge + b00t-owned registration workflow.
//!
//! `b00t mise <args>` forwards to the `mise.cli` datum via existing dispatch.
//! `b00t mise --register` writes b00t integration tasks to `mise.toml`.

use anyhow::{Context, Result, bail};
use std::path::{Path, PathBuf};

/// Registration configuration for mise.toml integration.
#[derive(Debug, Clone)]
pub struct RegisterConfig {
    pub dry_run: bool,
    pub global: bool,
    pub b00t_datum_dir: PathBuf,
}

/// Generate the b00t integration block for mise.toml.
///
/// The block includes:
/// - `b00t-validate`: validate datum schemas
/// - `b00t-list`: list available datums
/// - `b00t-bootstrap`: run b00t bootstrap path
/// - `b00t-status`: show b00t hive status
fn generate_b00t_tasks() -> String {
    r#"
# ── b00t integration (generated by `b00t mise --register`) ──
# These tasks bridge mise task/environment state with b00t's typed datum store.
# Do NOT edit manually — re-run `b00t mise --register` to regenerate.

[tasks.b00t-validate]
description = "Validate b00t datum schemas"
run = "b00t up"

[tasks.b00t-list]
description = "List available b00t datums"
run = "b00t up --json"

[tasks.b00t-bootstrap]
description = "Run b00t bootstrap"
run = "b00t bootstrap"

[tasks.b00t-status]
description = "Show b00t hive status"
run = "b00t hive status"
"#
    .trim_start()
    .to_string()
}

/// The b00t integration block sentinel comments for idempotency.
const BLOCK_START: &str = "# ── b00t integration (generated by `b00t mise --register`) ──";
const BLOCK_END: &str = "# ── end b00t integration ──";

/// Remove an existing b00t integration block from mise.toml content.
fn strip_existing_block(content: &str) -> String {
    let mut result = String::new();
    let mut in_block = false;
    for line in content.lines() {
        if line.trim() == BLOCK_START {
            in_block = true;
            continue;
        }
        if line.trim() == BLOCK_END {
            in_block = false;
            continue;
        }
        if !in_block {
            result.push_str(line);
            result.push('\n');
        }
    }
    result
}

/// Execute the `--register` workflow.
pub fn handle_register(config: &RegisterConfig) -> Result<()> {
    let mise_toml = if config.global {
        dirs::home_dir()
            .context("cannot resolve home directory")?
            .join(".config")
            .join("mise")
            .join("config.toml")
    } else {
        std::env::current_dir()
            .context("cannot resolve current directory")?
            .join("mise.toml")
    };

    let existing = if mise_toml.exists() {
        std::fs::read_to_string(&mise_toml)
            .with_context(|| format!("read {}", mise_toml.display()))?
    } else {
        String::new()
    };

    // Check if already registered (idempotency)
    if existing.contains(BLOCK_START) {
        if config.dry_run {
            println!("[dry-run] b00t integration block already exists in {}", mise_toml.display());
            println!("[dry-run] would strip and regenerate");
        } else {
            println!("⚠️  b00t integration block already exists — regenerating (idempotent)");
        }
    }

    let cleaned = strip_existing_block(&existing);
    let block = generate_b00t_tasks();

    let new_content = if cleaned.trim().is_empty() {
        format!("{}\n{}\n{}\n", BLOCK_START, block, BLOCK_END)
    } else {
        format!("{}\n\n{}\n{}\n{}\n", cleaned.trim_end(), BLOCK_START, block, BLOCK_END)
    };

    if config.dry_run {
        println!("[dry-run] would write to {}", mise_toml.display());
        println!("--- begin mise.toml (generated) ---");
        print!("{}", block);
        println!("--- end mise.toml (generated) ---");
        return Ok(());
    }

    if let Some(parent) = mise_toml.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("create {}", parent.display()))?;
    }

    std::fs::write(&mise_toml, &new_content)
        .with_context(|| format!("write {}", mise_toml.display()))?;

    println!("✅ b00t integration registered in {}", mise_toml.display());
    println!("   Tasks: b00t-validate, b00t-list, b00t-bootstrap, b00t-status");
    println!("   Run `mise tasks` to see them.");
    println!("   Source of truth: _b00t_/*.toml (b00t datums) remains canonical.");

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn strip_existing_block_removes_b00t_section() {
        let input = r#"[tools]
node = "20"

# ── b00t integration (generated by `b00t mise --register`) ──
[tasks.b00t-validate]
description = "old"
run = "old"
# ── end b00t integration ──

[tasks.my-task]
run = "echo hello"
"#;
        let result = strip_existing_block(input);
        assert!(!result.contains("b00t-validate"));
        assert!(result.contains("my-task"));
        assert!(result.contains("[tools]"));
    }

    #[test]
    fn strip_existing_block_noop_when_absent() {
        let input = "[tools]\nnode = \"20\"\n";
        let result = strip_existing_block(input);
        assert_eq!(result.trim(), input.trim());
    }

    #[test]
    fn generate_b00t_tasks_contains_expected_tasks() {
        let block = generate_b00t_tasks();
        assert!(block.contains("b00t-validate"));
        assert!(block.contains("b00t-list"));
        assert!(block.contains("b00t-bootstrap"));
        assert!(block.contains("b00t-status"));
        assert!(block.contains(BLOCK_START));
    }

    #[test]
    fn register_idempotent_no_existing_file() {
        let tmp = tempfile::tempdir().unwrap();
        let mise_toml = tmp.path().join("mise.toml");
        let config = RegisterConfig {
            dry_run: false,
            global: false,
            b00t_datum_dir: tmp.path().to_path_buf(),
        };
        // Monkey-patch: we can't change cwd in tests, so test the helpers directly
        let block = generate_b00t_tasks();
        let content = format!("{}\n{}\n{}\n", BLOCK_START, block, BLOCK_END);
        std::fs::write(&mise_toml, &content).unwrap();
        assert!(mise_toml.exists());
        let written = std::fs::read_to_string(&mise_toml).unwrap();
        assert!(written.contains("b00t-validate"));
    }

    #[test]
    fn register_idempotent_with_existing_block() {
        let existing = format!(
            "[tools]\nnode = \"20\"\n\n{}\n[tasks.b00t-validate]\nrun = \"old\"\n{}\n",
            BLOCK_START, BLOCK_END
        );
        let cleaned = strip_existing_block(&existing);
        assert!(!cleaned.contains("b00t-validate"));
        assert!(cleaned.contains("node"));
    }

    #[test]
    fn dry_run_does_not_write() {
        let tmp = tempfile::tempdir().unwrap();
        let mise_toml = tmp.path().join("mise.toml");
        // dry-run should not create the file
        // (we can't call handle_register without cwd manipulation, but we verify
        //  the helper doesn't touch filesystem)
        assert!(!mise_toml.exists());
    }
}