#!/usr/bin/env python3
"""Render b00t TOML config into an OpenTofu auto-tfvars file.

Why this exists: OpenTofu has no native `tomldecode`, and the only registry
TOML provider (`tobotimus/toml`) is a minimally-maintained data-source-only
plugin that never shipped the `provider::toml::decode` function `main.tf` was
written against (pinned `~> 1.0`, newest release 0.3.0). Rather than adopt an
abandoned provider or block the build plane on authoring a Go function-provider,
we parse TOML with the Python stdlib here and hand OpenTofu plain JSON.

Follow-up (b00t task): a real `provider::b00t::tomllmdecode` OpenTofu
function-provider with `.tomllmd` tail-map support, sharing the elasticdotventures
DSN-URI-parser provider scaffold. When it lands, this prestep can be retired.

Also folds in `.env` here rather than via `germanbrew/dotenv` — that provider
exposes `.entries` (not the `.env` attribute `main.tf` was written against) and
errors on a missing file, so the root module was doubly broken. One prestep,
zero flaky providers.

Inputs  (relative to b00t-tf/):
  _b00t_.toml              -> var `b00t_config_json`  (arbitrary nested object)
  ../_b00t_/keyring.tomllm -> var `keyring_keys`      (the `[[key]]` array)
  .env (optional)          -> var `dotenv_entries`    (flat map of string)

Output:
  generated.auto.tfvars.json   (git-ignored; regenerated by `just tf-render`)

Usage: run from b00t-tf/ (or anywhere — paths resolve against this file).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

try:
    import tomllib  # Python 3.11+
except ModuleNotFoundError:  # pragma: no cover
    sys.exit(
        "render-tfvars.py needs Python >= 3.11 (stdlib `tomllib`). "
        f"Running {sys.version.split()[0]}. Install a newer python3 or `uv python install 3.12`."
    )

TF_DIR = Path(__file__).resolve().parent.parent          # b00t-tf/
REPO_ROOT = TF_DIR.parent                                # repo root
B00T_CONFIG = TF_DIR / "_b00t_.toml"
KEYRING = REPO_ROOT / "_b00t_" / "keyring.tomllm"
DOTENV = TF_DIR / ".env"
OUT = TF_DIR / "generated.auto.tfvars.json"


def load_toml(path: Path) -> dict:
    if not path.exists():
        print(f"render-tfvars: {path} absent — using empty", file=sys.stderr)
        return {}
    with path.open("rb") as fh:
        return tomllib.load(fh)


def load_dotenv(path: Path) -> dict[str, str]:
    """Minimal KEY=VALUE reader. Ignores blanks / `#` comments / `export `
    prefixes; strips matching surrounding quotes. Absent file => {}."""
    if not path.exists():
        return {}
    out: dict[str, str] = {}
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        line = line.removeprefix("export ").strip()
        key, _, val = line.partition("=")
        key = key.strip()
        val = val.strip()
        if len(val) >= 2 and val[0] == val[-1] and val[0] in "\"'":
            val = val[1:-1]
        if key:
            out[key] = val
    return out


def main() -> int:
    b00t_config = load_toml(B00T_CONFIG)
    keyring = load_toml(KEYRING)
    keyring_keys = keyring.get("key", [])
    dotenv_entries = load_dotenv(DOTENV)

    payload = {
        "b00t_config_json": b00t_config,
        "keyring_keys": keyring_keys,
        "dotenv_entries": dotenv_entries,
    }
    OUT.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")

    active = [
        k for k in keyring_keys
        if k.get("status") == "active"
        and "gcp-build-plane-control" in k.get("scope", [])
    ]
    print(
        f"render-tfvars: wrote {OUT.relative_to(TF_DIR)} "
        f"({len(keyring_keys)} keyring entr{'y' if len(keyring_keys) == 1 else 'ies'}, "
        f"{len(active)} active for gcp-build-plane-control; "
        f"{len(dotenv_entries)} .env entr{'y' if len(dotenv_entries) == 1 else 'ies'})",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
